'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Telerik.GridExamplesVBNET.DataBinding.ProgrammaticHierarchy

    Partial Public Class DefaultVB

        '''<summary>
        '''form2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadScriptManager2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadScriptManager2 As Global.Telerik.Web.UI.RadScriptManager

        '''<summary>
        '''RadCodeBlock2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock2 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''RadGrid1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''RadClientDataSource2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadClientDataSource2 As Global.Telerik.Web.UI.RadClientDataSource
    End Class
End Namespace
